# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180411_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товар в заказах'},
        ),
    ]
