# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
